events {}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 8080;

        location = /api/auth/login {
            proxy_pass http://auth-service:8081/auth/login;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/courses {
            proxy_pass http://course-service:8082;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header X-Internal-API-Key $http_x_internal_api_key;
        }

        location /api/registrations {
            proxy_pass http://registration-service:8083/registrations;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location / {
            return 404;
        }
    }
}
