spring.application.name=api-gateway
server.port=8080
auth-service.base-url=${AUTH_SERVICE_BASE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_BASE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[1].id=course-public
spring.cloud.gateway.routes[1].uri=${COURSE_SERVICE_BASE_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/public/courses/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[2].id=course
spring.cloud.gateway.routes[2].uri=${COURSE_SERVICE_BASE_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/courses/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[3].id=registration
spring.cloud.gateway.routes[3].uri=${REGISTRATION_SERVICE_BASE_URL:http://localhost:8083}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/registrations/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[4].id=api-key-admin
spring.cloud.gateway.routes[4].uri=${AUTH_SERVICE_BASE_URL:http://localhost:8081}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/api-keys/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1
